Add tests for env struct
rafaeljesus/cron-srv pull request #14
Opened 2016-12-08 01:13 UTC by rafaeljesus

Add tests for env struct. It required some code refactoring for easier mocks and better interface contracts and return types

closes https://github.com/EmpregoLigado/cron-srv/issues/12

2016-12-08 03:45 UTC, aalvesjr requested changes

2016-12-08 03:45 UTC, aalvesjr commented on models/repo.go
> +type Repo interface {
:+1:

2016-12-08 03:45 UTC, aalvesjr commented on handlers/env_test.go
> +	"github.com/rafaeljesus/cron-srv/models"
:open_mouth: `rafael-jisas`

2016-12-08 03:45 UTC, aalvesjr commented on models/repo_mock.go
> +	crons := make([]*Cron, 0)
Have some reason for this `crons`? the tests didn't break without them

2016-12-08 07:30 UTC, rafaeljesus commented on handlers/env_test.go
> +	"github.com/rafaeljesus/cron-srv/models"
open_mouth

2016-12-08 18:21 UTC, rafaeljesus commented on models/repo_mock.go
> +	crons := make([]*Cron, 0)
This is necessary for `for _, cron := range cron` have data,

Yes it is not breaking because I am not asserting at `env.Sched.Create` I will find a way to ensure `env.Sched.Create` was called

2016-12-08 18:27 UTC, aalvesjr commented on models/repo_mock.go
> +	crons := make([]*Cron, 0)
👍

2016-12-08 18:29 UTC, rafaeljesus commented on models/repo_mock.go
> +	crons := make([]*Cron, 0)
Also the method signature is wrong I think i should be `(q *Query, crons *[]Cron )` I think, I will check that

2016-12-08 18:31 UTC, rafaeljesus commented on models/repo_mock.go
> +	crons := make([]*Cron, 0)
@aalvesjr your review was really useful 💋

2016-12-10 14:03 UTC, rafaeljesus commented
@aalvesjr Can you pls take a 👀  again?

2016-12-10 16:15 UTC, aalvesjr approved these changes
:clap:

2016-12-10 16:16 UTC, merged